### ISSUE TITLE
‼ update all configs for docker compose installation before 4.18.0 release

### ISSUE THREAD

**Issue by a-ryoo** [qameta/allure-docker-compose#22]
The release 4.18.0 is supposed to use email as a delivery medium for the invites.
Currently the configurations for the docker compose installation missing these parameters https://docs.qameta.io/allure-testops/getstarted/smtp/ and need to be updated prior to the release.

https://github.com/qameta/allure-docker-compose

**Comment by a-ryoo** [comment]
@alexey-bogdanov  Look up Helm repo and add ENV containing email

**Comment by alexey-bogdanov** [comment]
https://github.com/qameta/allure-docker-compose/pull/23

**Comment by mazzz1y** [comment]
@alexey-bogdanov 

It appears that this application uses the ALLURE_MAIL_FROM variable. I wasn't able to locate it in the documentation or examples, but it seems like this is the only variable with which I can set the 'Mail From' header.

Otherwise I get these errors:
```
2023-06-20 09:31:19.177 ERROR 8 --- [nio-8082-exec-2] i.qameta.allure.uaa.mail.MailOperations  : could not sent message admin invited you from null to mail@example.com with reply-to null
org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 550 Missing From header at envelope. Please fix email client settings or contact your system administrator.
```

**Comment by alexey-bogdanov** [comment]
@mazzz1y 
Thank you for your comment. The parameter has been added.
